// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/rpc/pb/kvstore.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	VectorClock   map[string]uint32      `protobuf:"bytes,2,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastUpdatedBy string                 `protobuf:"bytes,3,opt,name=last_updated_by,json=lastUpdatedBy,proto3" json:"last_updated_by,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *DataItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DataItem) GetVectorClock() map[string]uint32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *DataItem) GetLastUpdatedBy() string {
	if x != nil {
		return x.LastUpdatedBy
	}
	return ""
}

func (x *DataItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Items         []*DataItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicateRequest) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FetchItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItemRequest) Reset() {
	*x = FetchItemRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItemRequest) ProtoMessage() {}

func (x *FetchItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItemRequest.ProtoReflect.Descriptor instead.
func (*FetchItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *FetchItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItemResponse) Reset() {
	*x = FetchItemResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItemResponse) ProtoMessage() {}

func (x *FetchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItemResponse.ProtoReflect.Descriptor instead.
func (*FetchItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *FetchItemResponse) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FetchItemResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetMerkleTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumBuckets    int32                  `protobuf:"varint,1,opt,name=num_buckets,json=numBuckets,proto3" json:"num_buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerkleTreeRequest) Reset() {
	*x = GetMerkleTreeRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerkleTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerkleTreeRequest) ProtoMessage() {}

func (x *GetMerkleTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerkleTreeRequest.ProtoReflect.Descriptor instead.
func (*GetMerkleTreeRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *GetMerkleTreeRequest) GetNumBuckets() int32 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

type GetMerkleTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumBuckets    int32                  `protobuf:"varint,1,opt,name=num_buckets,json=numBuckets,proto3" json:"num_buckets,omitempty"`
	Nodes         [][]byte               `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerkleTreeResponse) Reset() {
	*x = GetMerkleTreeResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerkleTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerkleTreeResponse) ProtoMessage() {}

func (x *GetMerkleTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerkleTreeResponse.ProtoReflect.Descriptor instead.
func (*GetMerkleTreeResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{6}
}

func (x *GetMerkleTreeResponse) GetNumBuckets() int32 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

func (x *GetMerkleTreeResponse) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetBucketKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketIndex   int32                  `protobuf:"varint,1,opt,name=bucket_index,json=bucketIndex,proto3" json:"bucket_index,omitempty"`
	NumBuckets    int32                  `protobuf:"varint,2,opt,name=num_buckets,json=numBuckets,proto3" json:"num_buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketKeysRequest) Reset() {
	*x = GetBucketKeysRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketKeysRequest) ProtoMessage() {}

func (x *GetBucketKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketKeysRequest.ProtoReflect.Descriptor instead.
func (*GetBucketKeysRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *GetBucketKeysRequest) GetBucketIndex() int32 {
	if x != nil {
		return x.BucketIndex
	}
	return 0
}

func (x *GetBucketKeysRequest) GetNumBuckets() int32 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

type GetBucketKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketKeysResponse) Reset() {
	*x = GetBucketKeysResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketKeysResponse) ProtoMessage() {}

func (x *GetBucketKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketKeysResponse.ProtoReflect.Descriptor instead.
func (*GetBucketKeysResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{8}
}

func (x *GetBucketKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// VectorContext wraps a client's causal context so its absence is visible
// on the wire: a nil context ("build on whatever versions exist") and an
// empty one ("build on nothing") mean different things to Store.Put, and a
// bare proto3 map can't tell them apart.
type VectorContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]uint32      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorContext) Reset() {
	*x = VectorContext{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorContext) ProtoMessage() {}

func (x *VectorContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorContext.ProtoReflect.Descriptor instead.
func (*VectorContext) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *VectorContext) GetEntries() map[string]uint32 {
	if x != nil {
		return x.Entries
	}
	return nil
}

// CoordinatePutRequest carries a raw client write — value and causal
// context exactly as the client supplied them, no vector clock built yet —
// from a node that isn't one of key's replicas to one that is.
type CoordinatePutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`     // JSON, same encoding as DataItem.value
	Context       *VectorContext         `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // unset = nil context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatePutRequest) Reset() {
	*x = CoordinatePutRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatePutRequest) ProtoMessage() {}

func (x *CoordinatePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatePutRequest.ProtoReflect.Descriptor instead.
func (*CoordinatePutRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{10}
}

func (x *CoordinatePutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CoordinatePutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CoordinatePutRequest) GetContext() *VectorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CoordinatePutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatePutResponse) Reset() {
	*x = CoordinatePutResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatePutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatePutResponse) ProtoMessage() {}

func (x *CoordinatePutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatePutResponse.ProtoReflect.Descriptor instead.
func (*CoordinatePutResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{11}
}

// Ping is the heartbeat. The sender announces its own ID, its address (so a
// receiver that does not list it yet can fetch its membership), and the
// membership epoch and fingerprint it holds.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderAddress string                 `protobuf:"bytes,2,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{12}
}

func (x *PingRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PingRequest) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *PingRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PingRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// PingResponse names the answering node, so a caller can tell it reached the
// node it meant to, and its membership epoch and fingerprint.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PingResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{14}
}

// GetMembershipResponse is the answering node's current membership. The
// fingerprint is a claim: a receiver recomputes it from the members.
type GetMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Members       map[string]string      `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node ID -> address
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipResponse) Reset() {
	*x = GetMembershipResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipResponse) ProtoMessage() {}

func (x *GetMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{15}
}

func (x *GetMembershipResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GetMembershipResponse) GetMembers() map[string]string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetMembershipResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

var File_internal_rpc_pb_kvstore_proto protoreflect.FileDescriptor

const file_internal_rpc_pb_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/rpc/pb/kvstore.proto\x12\akvstore\"\xee\x01\n" +
	"\bDataItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12E\n" +
	"\fvector_clock\x18\x02 \x03(\v2\".kvstore.DataItem.VectorClockEntryR\vvectorClock\x12&\n" +
	"\x0flast_updated_by\x18\x03 \x01(\tR\rlastUpdatedBy\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"M\n" +
	"\x10ReplicateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.kvstore.DataItemR\x05items\"/\n" +
	"\x11ReplicateResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"$\n" +
	"\x10FetchItemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"R\n" +
	"\x11FetchItemResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.kvstore.DataItemR\x05items\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"7\n" +
	"\x14GetMerkleTreeRequest\x12\x1f\n" +
	"\vnum_buckets\x18\x01 \x01(\x05R\n" +
	"numBuckets\"N\n" +
	"\x15GetMerkleTreeResponse\x12\x1f\n" +
	"\vnum_buckets\x18\x01 \x01(\x05R\n" +
	"numBuckets\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\fR\x05nodes\"Z\n" +
	"\x14GetBucketKeysRequest\x12!\n" +
	"\fbucket_index\x18\x01 \x01(\x05R\vbucketIndex\x12\x1f\n" +
	"\vnum_buckets\x18\x02 \x01(\x05R\n" +
	"numBuckets\"+\n" +
	"\x15GetBucketKeysResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x8a\x01\n" +
	"\rVectorContext\x12=\n" +
	"\aentries\x18\x01 \x03(\v2#.kvstore.VectorContext.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"p\n" +
	"\x14CoordinatePutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x120\n" +
	"\acontext\x18\x03 \x01(\v2\x16.kvstore.VectorContextR\acontext\"\x17\n" +
	"\x15CoordinatePutResponse\"\x89\x01\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12%\n" +
	"\x0esender_address\x18\x02 \x01(\tR\rsenderAddress\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\"_\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\"\x16\n" +
	"\x14GetMembershipRequest\"\xd2\x01\n" +
	"\x15GetMembershipResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12E\n" +
	"\amembers\x18\x02 \x03(\v2+.kvstore.GetMembershipResponse.MembersEntryR\amembers\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x1a:\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8c\x04\n" +
	"\rKVReplication\x12B\n" +
	"\tReplicate\x12\x19.kvstore.ReplicateRequest\x1a\x1a.kvstore.ReplicateResponse\x12B\n" +
	"\tFetchItem\x12\x19.kvstore.FetchItemRequest\x1a\x1a.kvstore.FetchItemResponse\x12N\n" +
	"\rGetMerkleTree\x12\x1d.kvstore.GetMerkleTreeRequest\x1a\x1e.kvstore.GetMerkleTreeResponse\x12N\n" +
	"\rGetBucketKeys\x12\x1d.kvstore.GetBucketKeysRequest\x1a\x1e.kvstore.GetBucketKeysResponse\x12N\n" +
	"\rCoordinatePut\x12\x1d.kvstore.CoordinatePutRequest\x1a\x1e.kvstore.CoordinatePutResponse\x123\n" +
	"\x04Ping\x12\x14.kvstore.PingRequest\x1a\x15.kvstore.PingResponse\x12N\n" +
	"\rGetMembership\x12\x1d.kvstore.GetMembershipRequest\x1a\x1e.kvstore.GetMembershipResponseB*Z(distributed-kv-datastore/internal/rpc/pbb\x06proto3"

var (
	file_internal_rpc_pb_kvstore_proto_rawDescOnce sync.Once
	file_internal_rpc_pb_kvstore_proto_rawDescData []byte
)

func file_internal_rpc_pb_kvstore_proto_rawDescGZIP() []byte {
	file_internal_rpc_pb_kvstore_proto_rawDescOnce.Do(func() {
		file_internal_rpc_pb_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_pb_kvstore_proto_rawDesc), len(file_internal_rpc_pb_kvstore_proto_rawDesc)))
	})
	return file_internal_rpc_pb_kvstore_proto_rawDescData
}

var file_internal_rpc_pb_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_rpc_pb_kvstore_proto_goTypes = []any{
	(*DataItem)(nil),              // 0: kvstore.DataItem
	(*ReplicateRequest)(nil),      // 1: kvstore.ReplicateRequest
	(*ReplicateResponse)(nil),     // 2: kvstore.ReplicateResponse
	(*FetchItemRequest)(nil),      // 3: kvstore.FetchItemRequest
	(*FetchItemResponse)(nil),     // 4: kvstore.FetchItemResponse
	(*GetMerkleTreeRequest)(nil),  // 5: kvstore.GetMerkleTreeRequest
	(*GetMerkleTreeResponse)(nil), // 6: kvstore.GetMerkleTreeResponse
	(*GetBucketKeysRequest)(nil),  // 7: kvstore.GetBucketKeysRequest
	(*GetBucketKeysResponse)(nil), // 8: kvstore.GetBucketKeysResponse
	(*VectorContext)(nil),         // 9: kvstore.VectorContext
	(*CoordinatePutRequest)(nil),  // 10: kvstore.CoordinatePutRequest
	(*CoordinatePutResponse)(nil), // 11: kvstore.CoordinatePutResponse
	(*PingRequest)(nil),           // 12: kvstore.PingRequest
	(*PingResponse)(nil),          // 13: kvstore.PingResponse
	(*GetMembershipRequest)(nil),  // 14: kvstore.GetMembershipRequest
	(*GetMembershipResponse)(nil), // 15: kvstore.GetMembershipResponse
	nil,                           // 16: kvstore.DataItem.VectorClockEntry
	nil,                           // 17: kvstore.VectorContext.EntriesEntry
	nil,                           // 18: kvstore.GetMembershipResponse.MembersEntry
}
var file_internal_rpc_pb_kvstore_proto_depIdxs = []int32{
	16, // 0: kvstore.DataItem.vector_clock:type_name -> kvstore.DataItem.VectorClockEntry
	0,  // 1: kvstore.ReplicateRequest.items:type_name -> kvstore.DataItem
	0,  // 2: kvstore.FetchItemResponse.items:type_name -> kvstore.DataItem
	17, // 3: kvstore.VectorContext.entries:type_name -> kvstore.VectorContext.EntriesEntry
	9,  // 4: kvstore.CoordinatePutRequest.context:type_name -> kvstore.VectorContext
	18, // 5: kvstore.GetMembershipResponse.members:type_name -> kvstore.GetMembershipResponse.MembersEntry
	1,  // 6: kvstore.KVReplication.Replicate:input_type -> kvstore.ReplicateRequest
	3,  // 7: kvstore.KVReplication.FetchItem:input_type -> kvstore.FetchItemRequest
	5,  // 8: kvstore.KVReplication.GetMerkleTree:input_type -> kvstore.GetMerkleTreeRequest
	7,  // 9: kvstore.KVReplication.GetBucketKeys:input_type -> kvstore.GetBucketKeysRequest
	10, // 10: kvstore.KVReplication.CoordinatePut:input_type -> kvstore.CoordinatePutRequest
	12, // 11: kvstore.KVReplication.Ping:input_type -> kvstore.PingRequest
	14, // 12: kvstore.KVReplication.GetMembership:input_type -> kvstore.GetMembershipRequest
	2,  // 13: kvstore.KVReplication.Replicate:output_type -> kvstore.ReplicateResponse
	4,  // 14: kvstore.KVReplication.FetchItem:output_type -> kvstore.FetchItemResponse
	6,  // 15: kvstore.KVReplication.GetMerkleTree:output_type -> kvstore.GetMerkleTreeResponse
	8,  // 16: kvstore.KVReplication.GetBucketKeys:output_type -> kvstore.GetBucketKeysResponse
	11, // 17: kvstore.KVReplication.CoordinatePut:output_type -> kvstore.CoordinatePutResponse
	13, // 18: kvstore.KVReplication.Ping:output_type -> kvstore.PingResponse
	15, // 19: kvstore.KVReplication.GetMembership:output_type -> kvstore.GetMembershipResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_rpc_pb_kvstore_proto_init() }
func file_internal_rpc_pb_kvstore_proto_init() {
	if File_internal_rpc_pb_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_pb_kvstore_proto_rawDesc), len(file_internal_rpc_pb_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_pb_kvstore_proto_goTypes,
		DependencyIndexes: file_internal_rpc_pb_kvstore_proto_depIdxs,
		MessageInfos:      file_internal_rpc_pb_kvstore_proto_msgTypes,
	}.Build()
	File_internal_rpc_pb_kvstore_proto = out.File
	file_internal_rpc_pb_kvstore_proto_goTypes = nil
	file_internal_rpc_pb_kvstore_proto_depIdxs = nil
}
