// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: internal/rpc/pb/kvstore.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVReplication_Replicate_FullMethodName = "/kvstore.KVReplication/Replicate"
	KVReplication_FetchItem_FullMethodName = "/kvstore.KVReplication/FetchItem"
)

// KVReplicationClient is the client API for KVReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KVReplicationClient interface {
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
	FetchItem(ctx context.Context, in *FetchItemRequest, opts ...grpc.CallOption) (*FetchItemResponse, error)
}

type kVReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewKVReplicationClient(cc grpc.ClientConnInterface) KVReplicationClient {
	return &kVReplicationClient{cc}
}

func (c *kVReplicationClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, KVReplication_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVReplicationClient) FetchItem(ctx context.Context, in *FetchItemRequest, opts ...grpc.CallOption) (*FetchItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchItemResponse)
	err := c.cc.Invoke(ctx, KVReplication_FetchItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVReplicationServer is the server API for KVReplication service.
// All implementations must embed UnimplementedKVReplicationServer
// for forward compatibility.
type KVReplicationServer interface {
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	FetchItem(context.Context, *FetchItemRequest) (*FetchItemResponse, error)
	mustEmbedUnimplementedKVReplicationServer()
}

// UnimplementedKVReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVReplicationServer struct{}

func (UnimplementedKVReplicationServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedKVReplicationServer) FetchItem(context.Context, *FetchItemRequest) (*FetchItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchItem not implemented")
}
func (UnimplementedKVReplicationServer) mustEmbedUnimplementedKVReplicationServer() {}
func (UnimplementedKVReplicationServer) testEmbeddedByValue()                       {}

// UnsafeKVReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVReplicationServer will
// result in compilation errors.
type UnsafeKVReplicationServer interface {
	mustEmbedUnimplementedKVReplicationServer()
}

func RegisterKVReplicationServer(s grpc.ServiceRegistrar, srv KVReplicationServer) {
	// If the following call panics, it indicates UnimplementedKVReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVReplication_ServiceDesc, srv)
}

func _KVReplication_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVReplicationServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVReplication_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVReplicationServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVReplication_FetchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVReplicationServer).FetchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVReplication_FetchItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVReplicationServer).FetchItem(ctx, req.(*FetchItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVReplication_ServiceDesc is the grpc.ServiceDesc for KVReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvstore.KVReplication",
	HandlerType: (*KVReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Replicate",
			Handler:    _KVReplication_Replicate_Handler,
		},
		{
			MethodName: "FetchItem",
			Handler:    _KVReplication_FetchItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/pb/kvstore.proto",
}
