// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/rpc/pb/kvstore.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded Go value
	VectorClock   map[string]uint32      `protobuf:"bytes,2,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastUpdatedBy string                 `protobuf:"bytes,3,opt,name=last_updated_by,json=lastUpdatedBy,proto3" json:"last_updated_by,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *DataItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DataItem) GetVectorClock() map[string]uint32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *DataItem) GetLastUpdatedBy() string {
	if x != nil {
		return x.LastUpdatedBy
	}
	return ""
}

func (x *DataItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Item          *DataItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicateRequest) GetItem() *DataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FetchItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItemRequest) Reset() {
	*x = FetchItemRequest{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItemRequest) ProtoMessage() {}

func (x *FetchItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItemRequest.ProtoReflect.Descriptor instead.
func (*FetchItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *FetchItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItemResponse) Reset() {
	*x = FetchItemResponse{}
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItemResponse) ProtoMessage() {}

func (x *FetchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_pb_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItemResponse.ProtoReflect.Descriptor instead.
func (*FetchItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_pb_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *FetchItemResponse) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FetchItemResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_internal_rpc_pb_kvstore_proto protoreflect.FileDescriptor

const file_internal_rpc_pb_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/rpc/pb/kvstore.proto\x12\akvstore\"\xee\x01\n" +
	"\bDataItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12E\n" +
	"\fvector_clock\x18\x02 \x03(\v2\".kvstore.DataItem.VectorClockEntryR\vvectorClock\x12&\n" +
	"\x0flast_updated_by\x18\x03 \x01(\tR\rlastUpdatedBy\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"K\n" +
	"\x10ReplicateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x04item\x18\x02 \x01(\v2\x11.kvstore.DataItemR\x04item\"/\n" +
	"\x11ReplicateResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"$\n" +
	"\x10FetchItemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"R\n" +
	"\x11FetchItemResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.kvstore.DataItemR\x05items\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\x97\x01\n" +
	"\rKVReplication\x12B\n" +
	"\tReplicate\x12\x19.kvstore.ReplicateRequest\x1a\x1a.kvstore.ReplicateResponse\x12B\n" +
	"\tFetchItem\x12\x19.kvstore.FetchItemRequest\x1a\x1a.kvstore.FetchItemResponseB*Z(distributed-kv-datastore/internal/rpc/pbb\x06proto3"

var (
	file_internal_rpc_pb_kvstore_proto_rawDescOnce sync.Once
	file_internal_rpc_pb_kvstore_proto_rawDescData []byte
)

func file_internal_rpc_pb_kvstore_proto_rawDescGZIP() []byte {
	file_internal_rpc_pb_kvstore_proto_rawDescOnce.Do(func() {
		file_internal_rpc_pb_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_pb_kvstore_proto_rawDesc), len(file_internal_rpc_pb_kvstore_proto_rawDesc)))
	})
	return file_internal_rpc_pb_kvstore_proto_rawDescData
}

var file_internal_rpc_pb_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_rpc_pb_kvstore_proto_goTypes = []any{
	(*DataItem)(nil),          // 0: kvstore.DataItem
	(*ReplicateRequest)(nil),  // 1: kvstore.ReplicateRequest
	(*ReplicateResponse)(nil), // 2: kvstore.ReplicateResponse
	(*FetchItemRequest)(nil),  // 3: kvstore.FetchItemRequest
	(*FetchItemResponse)(nil), // 4: kvstore.FetchItemResponse
	nil,                       // 5: kvstore.DataItem.VectorClockEntry
}
var file_internal_rpc_pb_kvstore_proto_depIdxs = []int32{
	5, // 0: kvstore.DataItem.vector_clock:type_name -> kvstore.DataItem.VectorClockEntry
	0, // 1: kvstore.ReplicateRequest.item:type_name -> kvstore.DataItem
	0, // 2: kvstore.FetchItemResponse.items:type_name -> kvstore.DataItem
	1, // 3: kvstore.KVReplication.Replicate:input_type -> kvstore.ReplicateRequest
	3, // 4: kvstore.KVReplication.FetchItem:input_type -> kvstore.FetchItemRequest
	2, // 5: kvstore.KVReplication.Replicate:output_type -> kvstore.ReplicateResponse
	4, // 6: kvstore.KVReplication.FetchItem:output_type -> kvstore.FetchItemResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_rpc_pb_kvstore_proto_init() }
func file_internal_rpc_pb_kvstore_proto_init() {
	if File_internal_rpc_pb_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_pb_kvstore_proto_rawDesc), len(file_internal_rpc_pb_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_pb_kvstore_proto_goTypes,
		DependencyIndexes: file_internal_rpc_pb_kvstore_proto_depIdxs,
		MessageInfos:      file_internal_rpc_pb_kvstore_proto_msgTypes,
	}.Build()
	File_internal_rpc_pb_kvstore_proto = out.File
	file_internal_rpc_pb_kvstore_proto_goTypes = nil
	file_internal_rpc_pb_kvstore_proto_depIdxs = nil
}
